name: 'build and lint'
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2.4.2
        with: 
          node-version: '17.9.0'

      - name: 'make install'
        run: make install

      - name: 'make build'
        run: make build

      - name: 'make lint'
        run: make lint